[versions]
agp = "8.4.1"
kotlin = "1.9.21"
compose = "1.6.7"
compose-compiler = "1.5.6"
hilt = "2.51.1"
compose-material3 = "1.2.1"
lifecycle-compose = "2.7.0"
androidx-activity-compose = "1.9.0"
ksp = "1.9.21-1.0.16"
compose-destinations = "1.10.2"
coroutines = "1.7.3"
core-desugaring = "2.0.4"
retrofit = "2.9.0"
coil = "2.2.2"
room = "2.6.1"

androidx-core = "1.9.0"
androidx-appcompat = "1.5.1"
material = "1.7.0"
androidx-constraintlayout = "2.1.4"
androidx-lifecycle = "2.5.1"
jetpack-navigation = "2.5.3"

[libraries]

androidx-core =  { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat =  { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
jetpack-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "jetpack-navigation" }
jetpack-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "jetpack-navigation" }

# Coroutines
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

# Compose
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }

compose-destinations-core = { module = "io.github.raamcosta.compose-destinations:animations-core", version.ref = "compose-destinations" }
compose-destinations-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "compose-destinations" }

# Lifecycle
lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-compose" }

# Koin
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

# Retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

# Coil
coil = { module="io.coil-kt:coil", version.ref = "coil"}

# Room
room = { module="androidx.room:room-runtime", version.ref = "room"}
room-ktx = { module="androidx.room:room-ktx", version.ref = "room"}
room-compiler = { module="androidx.room:room-compiler", version.ref = "room"}

core-desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "core-desugaring" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

